# 自定义配置
custom:
  # 安全配置
  secure:
    # 演示模式开关
    demo-mode: false
    # 跳过鉴权开关
    skip-auth: true
  # 验证码配置
  captcha:
    enabled: false
    # 验证码类型
    type: image
    # 图形验证码类型，验证码类型为图形时需配置
    image-type: arithmetic

# knife4j增强配置
knife4j:
  # 是否开启生产环境保护策略
  production: false

# 数据库连接配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.101:3306/yasuo_test?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: yasuo_test
    password: yasuo_dev_vD87a9
    hikari:
      # 客户端从连接池等待连接的最大毫秒数
      connection-timeout: 20000
      # 连接池中维护的最小空闲连接数
      minimum-idle: 5
      # 最大连接池数大小
      maximum-pool-size: 20
      # 允许一个连接在连接池中闲置的最大毫秒数
      idle-timeout: 300000
      # 池中连接关闭后的最长生存毫秒数
      max-lifetime: 1200000
      # 从池中返回的连接的默认自动提交行为
      auto-commit: true
  cache:
    type: redis
  # redis配置
  data:
    redis:
      database: 2
      host: 192.168.2.101
      password: jhkdjhkjdhsIUTYURTU_bGCha4
      port: 6379
      timeout: 60s
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 200
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 5
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 60s

# 配置 Sa-Token 单独使用的 Redis 连接
sa-token:
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 192.168.2.101
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: jhkdjhkjdhsIUTYURTU_bGCha4
    # 连接超时时间
    timeout: 60s

# 线程池配置
thread:
  pool:
    # 设置核心线程数
    core-pool-size: 5
    # 设置最大线程数
    max-pool-size: 20
    # 设置缓冲队列大小
    queue-capacity: 100
    # 设置线程的最大空闲秒数
    keep-alive-seconds: 30
    # 是否允许核心线程超时
    allow-core-thread-timeout: true
    # 是否等待剩余任务完成后才关闭应用
    wait-for-tasks-to-complete-on-shutdown: true
    # 等待剩余任务完成的最大秒数
    await-termination-seconds: 60
    # 拒绝策略
    rejected-execution-handler: CallerRunsPolicy

# p6spy配置
decorator:
  datasource:
    enabled: true
